### ISSUE TITLE
Add picture icon to top page

### ISSUE THREAD

**Issue by Yuya-O-Nakagawa** [qulacs/qulacs-rtd#23]
On japanese top page, maybe we need "icon" pictures for `"Github repository | Slack Community | Study Material (Japanese)"` as in the previous webpage.

This makes it easy for readers to find those links, especially "quantum native dojo" which can serve as advanced use cases of qulacs.

**Comment by akpc** [comment]
Thank you this comments. I added the icons to the home page.
