### ISSUE TITLE
Markdown + Sphinxの検証をする

### ISSUE THREAD

**Issue by Hiroya-W** [qulacs/qulacs-rtd#86]
今まではrecommonmarkを作っていたけど、今はdeprecatedになっているらしい
https://github.com/readthedocs/recommonmark

その代わりに、mystがrecomendedになっているので、それを使ってMarkdown対応ができないか考えてみる
https://github.com/executablebooks/MyST-Parser

**Comment by Hiroya-W** [comment]
scikit-qulacsも参考に、

```py
# conf.py
extensions = [
    'myst_parser',
]

myst_enable_extensions = [
    "dollarmath",
]
```

を追記するだけで良さそう。reStructuredtextからMarkdownへの変換はpandocが使えると思うので、あらかた変換して調整してみる

**Comment by Hiroya-W** [comment]
Python APIを埋め込んでいるautodocに関しては、reStructuredtextの記法にしか対応しておらず、Markdownから触るにはラップする必要があるそう。
https://myst-parser.readthedocs.io/en/latest/faq/index.html#use-sphinx-ext-autodoc-in-markdown-files

pyRef/modules.rstが対応するのですが、このファイルに開発者が追記することはあまりなく、Markdownに変換すると余計にわかりにくくなりそうです。

**Comment by forest1040** [comment]
ありがとうございます。
autodocは、reStructuredtext記法のままで良さそうですね。
